version: "3.5"

networks:
  reverse-proxy-network:
    external:
      name: reverse-proxy-network
  php-fpm-network:

services:

  php-fpm:
    container_name: php-fpm
    image: php:fpm
    restart: on-failure
    ports:
      - 9000:9000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./webroot:/srv/webroot
      - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php-custom.conf:/usr/local/etc/php-fpm.d/custom.conf
    networks:
      - php-fpm-network
    labels:
      - "traefik.enable=false"

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: on-failure
    networks:
      - reverse-proxy-network
      - php-fpm-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./webroot:/srv/webroot
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:nginx.${DOMAIN}"
      - "traefik.docker.network=reverse-proxy-network"

  apache:
    container_name: apache2
    image: httpd:2.4.38
    restart: on-failure
    networks:
      - reverse-proxy-network
      - php-fpm-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./webroot:/usr/local/apache2/htdocs
      - ./apache-httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    links:
      - php-fpm
    depends_on:
      - php-fpm
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:apache.${DOMAIN}"
      - "traefik.docker.network=reverse-proxy-network"

