version: "3.5"

volumes:
  mariadb-data:

services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: mariadb.Dockerfile
    hostname: ${MARIADB_HOSTNAME}
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${MARIADB_PORT}:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=false"