#**************************#
#*  Traefik Configuration *#
  #**************************#

#**************************#
#*      Entrypoints       *#
#**************************#
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
      permanent = true

[entryPoints.https]
  address = ":443"
  compress = true
  [entryPoints.https.tls]


#**************************#
#*       FrontEnds        *#
#**************************#

#**************************#
#*       BackEnds         *#
#**************************#
